const translations = {
    // English Translations
    en: {
        // General
        settingsLink: "← Settings",
        backLink: "← Back",
        // index.html
        totalIncomeLabel: "Total Income",
        totalExpenseLabel: "Total Expense",
        balanceLabel: "Final Balance",
        addTransactionLabel: "Add New Transaction",
        descriptionPlaceholder: "e.g., Bought Coffee",
        categoryPlaceholder: "Choose a category",
        tagsPlaceholder: "Tags (comma separated)",
        quantityPlaceholder: "Item quantity (e.g., 2)",
        pricePlaceholder: "Price per item (e.g., 25000)",
        incomeOption: "Income",
        expenseOption: "Expense",
        addButton: "Add",
        selectCategoryOption: "Select category",
        searchTransactionsPlaceholder: "Search description, category or tags",
        filterCategoryPlaceholder: "Filter by category",
        filterAmountPlaceholder: "Max amount",
        clearFiltersButton: "Clear",
        noMatchingTransactions: "No matching transactions",
        categoryFood: "Food",
        categoryBills: "Bills",
        categoryTransport: "Transport",
        categorySavings: "Savings",
        categoryOther: "Other",
        categoryHeader: "Category",
        tagsHeader: "Tags",
        historyLabel: "Transaction History",
        dateHeader: "Date",
        descriptionHeader: "Description",
        amountHeader: "Total Price",
        quantityHeader: "Quantity",
        typeHeader: "Type",
        actionHeader: "Action",
        noTransactions: "No transactions yet",
        saveLocalBtn: "Save to App",
        downloadTxtBtn: "Save as .txt",
        downloadMdBtn: "Save as .md",
        notesPlaceholder: "Write your notes, ideas, or shopping lists here...",
        notesSavedAlert: "Notes saved!",
        // script.js alerts
        validationAlert: "All fields must be filled!",
        deleteConfirm: "Are you sure you want to delete this transaction?",
        // settings.html
        settingsTitle: "Settings",
        themeLabel: "Display Theme",
        lightModeOption: "Light Mode",
        darkModeOption: "Dark Mode",
        currencyLabel: "Currency Symbol",
        currencyPlaceholder: "Example: $",
        saveButton: "Save",
        dataMgmtLabel: "Data Management",
        resetButton: "Delete All Data",
        showCalcLabel: "Show Quick Calculator",
        languageLabel: "Language",
        // settings.js alerts
        currencySavedAlert: "Currency symbol saved successfully!",
        currencyEmptyAlert: "Symbol cannot be empty!",
        resetConfirm1: "Are you sure you want to delete all data? This is a permanent action!",
        resetConfirm2: "Really sure? This action cannot be undone.",
        resetSuccessAlert: "All transaction data has been successfully deleted.",
        // navigation bar
        quickCalculatorTitle: "Quick Calculator",
        transactionsTitle: "Transactions",
        quickCalculatorNav: "Quick Calculator",
        transactionsNav: "Transactions",
    },
    // Indonesian Translations
    id: {
        // General
        settingsLink: "← Pengaturan",
        backLink: "← Kembali",
        // index.html
        totalIncomeLabel: "Total Pemasukan",
        totalExpenseLabel: "Total Pengeluaran",
        balanceLabel: "Saldo Akhir",
        addTransactionLabel: "Tambah Transaksi Baru",
        descriptionPlaceholder: "Contoh: Beli Kopi",
        categoryPlaceholder: "Pilih kategori",
        tagsPlaceholder: "Tag (pisahkan dengan koma)",
        quantityPlaceholder: "Jumlah Barang (contoh: 2)",
        pricePlaceholder: "Harga Satuan (contoh: 25000)",
        incomeOption: "Pemasukan",
        expenseOption: "Pengeluaran",
        addButton: "Tambah",
        selectCategoryOption: "Pilih kategori",
        searchTransactionsPlaceholder: "Cari deskripsi, kategori, atau tag",
        filterCategoryPlaceholder: "Saring berdasarkan kategori",
        filterAmountPlaceholder: "Jumlah maksimal",
        clearFiltersButton: "Bersihkan",
        noMatchingTransactions: "Tidak ada transaksi yang cocok",
        categoryFood: "Makanan",
        categoryBills: "Tagihan",
        categoryTransport: "Transport",
        categorySavings: "Tabungan",
        categoryOther: "Lainnya",
        categoryHeader: "Kategori",
        tagsHeader: "Tag",
        historyLabel: "Riwayat Transaksi",
        dateHeader: "Tanggal",
        descriptionHeader: "Deskripsi",
        amountHeader: "Jumlah Harga",
        quantityHeader: "Jumlah Barang",
        typeHeader: "Tipe",
        actionHeader: "Aksi",
        noTransactions: "Belum ada transaksi",
        saveLocalBtn: "Simpan di Aplikasi",
        downloadTxtBtn: "Simpan sebagai .txt",
        downloadMdBtn: "Simpan sebagai .md",
        notesPlaceholder: "Tulis catatan, ide, atau daftar belanja di sini...",
        notesSavedAlert: "Catatan berhasil disimpan!",
        // script.js alerts
        validationAlert: "Semua kolom wajib diisi!",
        deleteConfirm: "Yakin mau hapus transaksi ini?",
        // settings.html
        settingsTitle: "Pengaturan",
        themeLabel: "Tema Tampilan",
        lightModeOption: "Light Mode",
        darkModeOption: "Dark Mode",
        currencyLabel: "Simbol Mata Uang",
        currencyPlaceholder: "Contoh: Rp",
        saveButton: "Simpan",
        dataMgmtLabel: "Manajemen Data",
        resetButton: "Hapus Semua Data",
        showCalcLabel: "Tampilkan Kalkulator Cepat",
        languageLabel: "Bahasa",
        // settings.js alerts
        currencySavedAlert: "Simbol mata uang berhasil disimpan!",
        currencyEmptyAlert: "Simbol tidak boleh kosong!",
        resetConfirm1: "Apakah anda yakin ingin menghapus data? Ini tindakan permanen!",
        resetConfirm2: "Yakin? Tindakan ini tidak bisa dibatalkan.",
        resetSuccessAlert: "Semua data transaksi berhasil dihapus.",
        // navigation bar
        quickCalculatorTitle: "Kalkulator Cepat",
        transactionsTitle: "Transaksi",
        quickCalculatorNav: "Kalkulator Cepat",
        transactionsNav: "Transaksi",
    }
};